version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: rubux
      POSTGRES_USER: rubux
      POSTGRES_PASSWORD: rubux_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  bot:
    build: .
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://rubux:rubux_pass@postgres/rubux
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  redis_data:
  pg_data:
